### ISSUE TITLE
温度折线图问题

### ISSUE THREAD

**Issue by ZhongYangdev** [wdsqjq/FengYunWeather#13]
作者你好！
我使用了你的 温度折线图控件 TempChart，当我传入数据后折线图的内容超出了我给定范围，如下图所示：
![IMG_20220609_105836](https://user-images.githubusercontent.com/63274531/172755696-89793e09-16bd-41e1-a178-d6a7090e36a1.jpg)
![IMG_20220609_110033](https://user-images.githubusercontent.com/63274531/172755700-6c77c141-6963-4c9b-8bdf-5ee241868acd.jpg)
请问你知道是什么情况吗？

**Comment by wdsqjq** [comment]
需要先传数据中温度的最大值和最小值进去，你看看你是不是传的不对

**Comment by zhanghao5683934** [comment]
您好，您所说的这个项目是我fork的项目，原项目链接是：https://github.com/wdsqjq/FengYunWeather，作者介绍链接为：https://github.com/wdsqjq，您可以咨询一下原作者




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wdsqjq/FengYunWeather"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月9日(星期四) 中午11:20
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [wdsqjq/FengYunWeather] 温度折线图问题 (Issue #13)





 
需要先传数据中温度的最大值和最小值进去，你看看你是不是传的不对

**Comment by wdsqjq** [comment]
额，你觉得我不是原作者吗？

**Comment by zhanghao5683934** [comment]
不好意思，刚刚发出去才发现，收件人的名称就是dajuzi，撤还没办法撤回来啦！(ˉ▽ˉ；)...
话说，fork的项目，有人提问的话，我也会被抄送邮件信息吗？之前没碰到过咨询的


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wdsqjq/FengYunWeather"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月9日(星期四) 中午11:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wdsqjq/FengYunWeather] 温度折线图问题 (Issue #13)





 
额，你觉得我不是原作者吗？

**Comment by ZhongYangdev** [comment]
> 需要先传数据中温度的最大值和最小值进去，你看看你是不是传的不对

已经解决了，是要先设置最大温度和最小温度范围。我只取了结果集合中第一条数据的最大值和最小值。没有对整个集合遍历取最大和最小，所以才导致范围超出了。
感谢答复！
这个风云天气做的真的很棒，给了我很大的参考价值，再次感谢！
