### ISSUE TITLE
Activity与Fragment视图更新问题

### ISSUE THREAD

**Issue by ZhongYangdev** [wdsqjq/FengYunWeather#14]
作者你好，我在Fragment中**请求并显示**天气数据，当数据请求到时需要通过天气代码来更新Activity的背景图片与动效。我使用协程与你一致的写法，更新首页ViewModel中的**天气代码**字段，明明在Activity中监听了天气代码变化，但就是没反应。

步骤代码如下：

fragment中请求到天气信息数据后，通知Activity更新UI
```
//更新天气背景
lifecycleScope.launchWhenResumed {
    homeViewModel.setSkyCon(realtime.skycon)
}
```
ViewModel中设置天气代码
```
val skyConData = MutableLiveData<String>()//天气代码

//设置天气代码
fun setSkyCon(skyCon: String) {
    skyConData.postValue(skyCon)
}
```
在Activity的 *onCreate()* 方法中观察天气代码，天气代码变化时调用 *updContent()* 方法更新背景和动效内容
```
homeViewModel.skyConData.observe(this, ::updContent)
```

Activity中的天气背景并没有根据天气代码变化而更新。想请教一下，您知道问题出在哪儿吗？

**Comment by wdsqjq** [comment]
你fragment中的homeViewModel是怎么初始化的？fragment和Activity的VewModel需要用同一个viewModelStoreOwner初始化才行

**Comment by ZhongYangdev** [comment]
> 你fragment中的homeViewModel是怎么初始化的？fragment和Activity的VewModel需要用同一个viewModelStoreOwner初始化才行

已解决，感谢答复！
正如您所言，fragment与Activity不是同一个viewModelStoreOwner，所以才导致无法动态更新。
